//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoccerWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhAnh
    {
        public int ID { get; set; }
        public int IDSP { get; set; }
        public string URL { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
